token:
  expiration_time: 86400000
  secret: usertokenusertokenusertokenusertokenusertoken

gateway:
  ip: 192.168.0.8
 
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}7d5333970bddc001c36b822421a7b231a6a8a3ffa73b75d86b5e5bbc6532f2c9'
    
order_service:
   url: http://ORDER-SERVICE/order-service/%s/orders