server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/IdeaProjects/msa/native-file-repo

        git:
          default-label: master
#          uri: file://C:\Users\chemi\IdeaProjects\git-local-repo
          uri: https://github.com/lacram/spring-cloud-config.git
  config:
    import: classpath:/bootstrap.yml

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh